import os

AWS_REGION = os.getenv("AWS_REGION", "us-east-1")
BEDROCK_REGION = os.getenv("BEDROCK_REGION", AWS_REGION)
MODEL_ID = os.getenv("MODEL_ID", "anthropic.claude-3-5-sonnet-20240620-v1:0")

GATEWAY_CONFIG_PATH = os.getenv("GATEWAY_CONFIG_PATH", "agentcore/gateway_config.json")
GATEWAY_URL = os.getenv("GATEWAY_URL", "")
GATEWAY_REGION = os.getenv("GATEWAY_REGION", AWS_REGION)

RCA_BUCKET = os.getenv("RCA_BUCKET", "")
RCA_PREFIX = os.getenv("RCA_PREFIX", "rca/")

STRANDS_ENABLE_LLM = os.getenv("STRANDS_ENABLE_LLM", "0") == "1"

AGENTCORE_POLICY_ENABLED = os.getenv("AGENTCORE_POLICY_ENABLED", "0") == "1"
AGENTCORE_POLICY_ENGINE_ID = os.getenv("AGENTCORE_POLICY_ENGINE_ID", "")
AGENTCORE_POLICY_STRICT = os.getenv("AGENTCORE_POLICY_STRICT", "0") == "1"

AGENTCORE_EVALUATION_ENABLED = os.getenv("AGENTCORE_EVALUATION_ENABLED", "0") == "1"
AGENTCORE_EVALUATOR_ID = os.getenv("AGENTCORE_EVALUATOR_ID", "")
AGENTCORE_EVALUATION_STRICT = os.getenv("AGENTCORE_EVALUATION_STRICT", "0") == "1"
AGENTCORE_MIN_EVAL_SCORE = float(os.getenv("AGENTCORE_MIN_EVAL_SCORE", "0.7"))
